require("berwyn.plugins-setup")
require("berwyn.core.options")
require("berwyn.core.keymaps")
require("berwyn.core.colorscheme")
require("berwyn.plugins.comment")
require("berwyn.plugins.nvim-tree")
require("berwyn.plugins.lualine")
require("berwyn.plugins.telescope")
require("berwyn.plugins.nvim-cmp")
require("berwyn.plugins.lsp.mason")
require("berwyn.plugins.lsp.lspsaga")
require("berwyn.plugins.lsp.lspconfig")
require("berwyn.plugins.lsp.null-ls")
require("berwyn.plugins.autopairs")
require("berwyn.plugins.treesitter")
require("berwyn.plugins.gitsigns")
require("berwyn.plugins.toggleterm")
require("berwyn.plugins.mini-move")
require("berwyn.plugins.lsp.lsplens")
require("berwyn.plugins.harpoon")
require("berwyn.plugins.indent-blankline")
require("berwyn.plugins.venv-selector")

-- Config V2

-- require("berwyn_v2.core")
-- require("berwyn_v2.lazy")
